pipeline:
  deploy:
    image: docker/compose
    commands:
      - ls /opt
      - ls /opt/ponder
      - set -a && source /opt/ponder/.dev.env && set +a
      - docker compose build
      - docker compose up -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/ponder:/opt/ponder
branches:
  include: [dev, stg, prd]
