pipeline:
  deploy:
    image: docker/compose
    commands:
      - "set -a && source /.dev.env && set +a"
      - "docker-compose build"
      - "docker-compose up -d"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/ponder/.dev.env:/.dev.env
branches:
  include: [dev, stg, prd]
