pipeline:
  deploy:
    image: docker/compose:1.22.0
    commands:
      - "set -a && source /opt/ponder/.${DRONE_BRANCH}.env && set +a"
      - "printenv"
      - "docker-compose build"
      - "docker compose up -d"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/ponder:/opt/ponder
branches:
  include: [dev, stg, prd]
