version: "3.5"
services:
  api:
    build: ./api
    image: keybra/ponder_api
    restart: always
    depends_on:
      - database
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/usr/src/api
    networks:
      - default
      - proxy
    environment:
      - HOST
      - NODE_ENV
      - API_PORT
      - DATABASE_URL
      - DATABASE_POOL_MIN
      - DATABASE_POOL_MAX
      - DEBUG=knex*
  graphql:
    build: ./graphql
    image: keybra/ponder_graphql
    depends_on:
      - api
    restart: always
    ports:
      - "${GRAPHQL_PORT}:${GRAPHQL_PORT}"
    volumes:
      - .:/usr/src/graphql
    networks:
      - default
      - proxy
    environment:
      - HOST
      - NODE_ENV
      - GRAPHQL_PORT
      - API_URL
    labels:
      - traefik.backend=graphql
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:${ENV_ID}-gql.ponder-app.com
      - traefik.enable=true
      - traefik.port=${GRAPHQL_PORT}
  database:
    image: postgres
    restart: always
    command: -p ${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - default
      - proxy
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
volumes:
  data: {}
networks:
  proxy:
    external: true
