version: "3.5"
services:
  web:
    build: ./web
    image: keybra/ponder_web
    restart: always
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - .:/usr/src/web
    networks:
      - proxy
    environment:
      - HOST
      - NODE_ENV
      - WEB_PORT
    labels:
      - traefik.backend=web
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:www.ponder-app.com
      - traefik.enable=true
      - traefik.port=${WEB_PORT}
  api:
    build: ./api
    image: keybra/ponder_api
    depends_on:
      - postgres
    restart: always
    expose:
      - "${API_PORT}"
    volumes:
      - .:/usr/src/api
    networks:
      - proxy
    environment:
      - HOST
      - NODE_ENV
      - API_PORT
      - POSTGRES_URL
  graphql:
    build: ./graphql
    image: keybra/ponder_graphql
    depends_on:
      - api
    restart: always
    expose:
      - "${GRAPHQL_PORT}"
    volumes:
      - .:/usr/src/graphql
    networks:
      - proxy
    environment:
      - HOST
      - NODE_ENV
      - GRAPHQL_PORT
      - API_URL
    labels:
      - traefik.backend=graphql
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:${ENV_ID}-gql.ponder-app.com
      - traefik.enable=true
      - traefik.port=${GRAPHQL_PORT}
  postgres:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - proxy
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
volumes:
  data: {}
networks:
  proxy:
    external: true
