version: "3.5"
services:
  ponder_api:
    image: keybra/ponder_api
    container_name: ponder_${ENV_ID}_api
    depends_on:
      - ponder_postgres
    restart: always
    networks:
      - web
      - ponder_network
    expose:
      - 3100
    env_file:
      - ${ENV_ID}.env
  ponder_graphql:
    image: keybra/ponder_graphql
    container_name: ponder_${ENV_ID}_graphql
    depends_on:
      - ponder_api
    restart: always
    networks:
      - web
      - ponder_network
    expose:
      - 3000
    labels:
      - traefik.backend=ponder_graphql
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:${ENV_ID}-gql.ponder-app.com
      - traefik.enable=true
      - traefik.port=3000
    env_file:
      - ${ENV_ID}.env
  ponder_postgres:
    image: postgres
    container_name: ponder_${ENV_ID}_postgres
    restart: always
    networks:
      - web
      - ponder_network
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ${ENV_ID}.env
    labels:
      - traefik.backend=ponder_postgres
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:${ENV_ID}-pg.ponder-app.com
      - traefik.enable=true
      - traefik.port=5432
volumes:
  data: {}
networks:
  ponder_network:
    name: ponder_${ENV_ID}_network
  web:
    external: true
