'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      'Poems',
      [
        {
          id: 1,
          authorId: 1,
          title: 'Ode on a Grecian Urn',
          teaser:
            "Thou still unravish'd bride of quietness,\nThou foster-child of silence and slow time",
          lines: [
            "Thou still unravish'd bride of quietness,",
            'Thou foster-child of silence and slow time,',
            'Sylvan historian, who canst thus express',
            'A flowery tale more sweetly than our rhyme:',
            "What leaf-fring'd legend haunts about thy shape",
            'Of deities or mortals, or of both,',
            'In Tempe or the dales of Arcady?',
            'What men or gods are these? What maidens loth?',
            'What mad pursuit? What struggle to escape?',
            'What pipes and timbrels? What wild ecstasy?',
            '',
            'Heard melodies are sweet, but those unheard',
            'Are sweeter; therefore, ye soft pipes, play on;',
            "Not to the sensual ear, but, more endear'd,",
            'Pipe to the spirit ditties of no tone:',
            'Fair youth, beneath the trees, thou canst not leave',
            'Thy song, nor ever can those trees be bare;',
            'Bold Lover, never, never canst thou kiss,',
            'Though winning near the goal yet, do not grieve;',
            'She cannot fade, though thou hast not thy bliss,',
            'For ever wilt thou love, and she be fair!',
            '',
            'Ah, happy, happy boughs! that cannot shed',
            'Your leaves, nor ever bid the Spring adieu;',
            'And, happy melodist, unwearied,',
            'For ever piping songs for ever new;',
            'More happy love! more happy, happy love!',
            "For ever warm and still to be enjoy'd,",
            'For ever panting, and for ever young;',
            'All breathing human passion far above,',
            "That leaves a heart high-sorrowful and cloy'd,",
            'A burning forehead, and a parching tongue.',
            '',
            'Who are these coming to the sacrifice?',
            'To what green altar, O mysterious priest,',
            "Lead'st thou that heifer lowing at the skies,",
            'And all her silken flanks with garlands drest?',
            'What little town by river or sea shore,',
            'Or mountain-built with peaceful citadel,',
            'Is emptied of this folk, this pious morn?',
            'And, little town, thy streets for evermore',
            'Will silent be; and not a soul to tell',
            "Why thou art desolate, can e'er return.",
            '',
            'O Attic shape! Fair attitude! with brede',
            'Of marble men and maidens overwrought,',
            'With forest branches and the trodden weed;',
            'Thou, silent form, dost tease us out of thought',
            'As doth eternity: Cold Pastoral!',
            'When old age shall this generation waste,',
            'Thou shalt remain, in midst of other woe',
            "Than ours, a friend to man, to whom thou say'st,",
            '"Beauty is truth, truth beauty,—that is all',
            'Ye know on earth, and all ye need to know."',
          ],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 2,
          authorId: 2,
          title: 'Ozymandias',
          teaser:
            'I met a traveller from an antique land,\nWho said—“Two vast and trunkless legs of stone',
          lines: [
            'I met a traveller from an antique land,',
            'Who said—“Two vast and trunkless legs of stone',
            'Stand in the desert. . . . Near them, on the sand,',
            'Half sunk a shattered visage lies, whose frown,',
            'And wrinkled lip, and sneer of cold command,',
            'Tell that its sculptor well those passions read',
            'Which yet survive, stamped on these lifeless things,',
            'The hand that mocked them, and the heart that fed;',
            'And on the pedestal, these words appear:',
            'My name is Ozymandias, King of Kings;',
            'Ozymandias',
            'Look on my Works, ye Mighty, and despair!',
            'Nothing beside remains. Round the decay',
            'Of that colossal Wreck, boundless and bare',
            'The lone and level sands stretch far away.”',
          ],
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Poems', null, {});
  },
};
