version: "3.5"

services:
  drone_server:
    image: drone/drone:0.7
    ports:
      - "8000:8000"
    volumes:
      - /var/lib/drone:/var/lib/drone
    restart: always
    networks:
      - default
      - proxy
    env_file:
      - .server.env
    labels:
      - traefik.backend=drone_server
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:drone.ponder-app.com
      - traefik.enable=true
      - traefik.port=8000

  drone_agent:
    image: drone/drone:0.7
    command: agent
    depends_on:
      - drone_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - proxy
    restart: always
    env_file:
      - .agent.env

networks:
  proxy:
    external: true
