version: "3.5"

services:
  drone_server:
    image: drone/drone:latest
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - data:/var/lib/drone
    restart: always
    networks:
      - default
      - proxy
    env_file:
      - .server.env
    labels:
      - traefik.backend=drone_server
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:drone.ponder-app.com
      - traefik.enable=true
      - traefik.port=8000

  drone_agent:
    image: drone/agent:latest
    command: agent
    depends_on:
      - drone_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - proxy
    restart: always
    env_file:
      - .agent.env

volumes:
  data: {}

networks:
  proxy:
    external: true
